  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
  permissions:
    contents: write
    pages: write
    id-token: write
    pull-requests: write
    issues: write
    repository-projects: write
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: setup-node
            uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Install packages
            run: npm i
          - name: Deploy
            run: npm run deploy
